language: python
python:
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements.txt -r requirements-test.txt
notifications:
  irc:
    channels: "irc.freenode.org#vitasso"
    on_success: change
    on_failure: change
